-- contradictions.db schema
-- Generated by dumpDbToSql.js — do not edit by hand; re-run the script.

PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS bible_references;
DROP TABLE IF EXISTS answers;
DROP TABLE IF EXISTS contradictions;
DROP TABLE IF EXISTS scholarly_consensus_levels;
DROP TABLE IF EXISTS contradiction_types;
DROP TABLE IF EXISTS categories;

CREATE TABLE categories (
            id   INTEGER PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL
        );

CREATE TABLE contradiction_types (
            id   INTEGER PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL
        );

CREATE TABLE scholarly_consensus_levels (
            id   INTEGER PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL
        );

CREATE TABLE contradictions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            question TEXT NOT NULL,
            question_url TEXT NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        , summary TEXT, commentary TEXT, scholarship TEXT, recommend_delete INTEGER DEFAULT 0, delete_reason TEXT, category_id INTEGER REFERENCES categories(id), testament_scope TEXT, books_in_tension TEXT, contradiction_type_id INTEGER REFERENCES contradiction_types(id), difficulty_level INTEGER, notoriety_level INTEGER, scholarly_consensus_id INTEGER REFERENCES scholarly_consensus_levels(id), textual_variant_involved INTEGER, variant_description TEXT, critical_apparatus_ref TEXT);

CREATE TABLE answers (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            contradiction_id INTEGER NOT NULL,
            answer TEXT NOT NULL,
            answer_explanation TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (contradiction_id) REFERENCES contradictions(id)
        );

CREATE TABLE bible_references (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            answer_id INTEGER NOT NULL,
            reference TEXT NOT NULL,
            FOREIGN KEY (answer_id) REFERENCES answers(id)
        );

CREATE INDEX idx_answers_contradiction ON answers(contradiction_id);
CREATE INDEX idx_references_answer ON bible_references(answer_id);
CREATE INDEX idx_contradictions_category ON contradictions(category_id);
CREATE INDEX idx_contradictions_type ON contradictions(contradiction_type_id);
CREATE INDEX idx_contradictions_consensus ON contradictions(scholarly_consensus_id);
