/**
 * dumpDbToSql.js — Export contradictions.db to portable SQL text.
 *
 * Produces two files in db/:
 *   db/schema.sql  — DROP/CREATE for every table + index (verbatim from sqlite_master)
 *   db/data.sql    — INSERT statements for every row, wrapped in a transaction
 *
 * Together they fully recreate the database. Regenerate after any data change:
 *   node dumpDbToSql.js
 *
 * Env overrides: DB_PATH (default ./contradictions.db), OUT_DIR (default ./db)
 */
const fs = require('fs');
const path = require('path');
const initSqlJs = require('sql.js');

const DB_PATH = process.env.DB_PATH || './contradictions.db';
const OUT_DIR = process.env.OUT_DIR || './db';

// Parent-first so the data file loads cleanly even with foreign keys enforced.
const TABLE_ORDER = ['categories', 'contradiction_types', 'scholarly_consensus_levels', 'contradictions', 'answers', 'bible_references'];

function sqlValue(v) {
    if (v === null || v === undefined) return 'NULL';
    if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
    if (typeof v === 'bigint') return v.toString();
    if (v instanceof Uint8Array) {
        let hex = '';
        for (const b of v) hex += b.toString(16).padStart(2, '0');
        return `X'${hex}'`;
    }
    return `'${String(v).replace(/'/g, "''")}'`;
}

async function main() {
    const SQL = await initSqlJs();
    const db = new SQL.Database(fs.readFileSync(DB_PATH));

    // ---- collect schema objects from sqlite_master ----
    const master = db.exec(
        "SELECT type, name, tbl_name, sql FROM sqlite_master " +
        "WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL"
    );
    const objects = master.length
        ? master[0].values.map(([type, name, tblName, sql]) => ({ type, name, tblName, sql }))
        : [];

    const tableSql = new Map(objects.filter(o => o.type === 'table').map(o => [o.name, o.sql]));
    const indexes = objects.filter(o => o.type === 'index');

    const tables = TABLE_ORDER.filter(t => tableSql.has(t));
    // Append any tables not in the explicit order, so nothing is silently dropped.
    for (const o of objects) {
        if (o.type === 'table' && !tables.includes(o.name)) tables.push(o.name);
    }

    // ---- schema.sql ----
    const schemaLines = [
        '-- contradictions.db schema',
        '-- Generated by dumpDbToSql.js — do not edit by hand; re-run the script.',
        '',
        'PRAGMA foreign_keys = OFF;',
        ''
    ];
    for (const name of [...tables].reverse()) schemaLines.push(`DROP TABLE IF EXISTS ${name};`);
    schemaLines.push('');
    for (const name of tables) schemaLines.push(`${tableSql.get(name)};`, '');
    for (const idx of indexes) schemaLines.push(`${idx.sql};`);
    schemaLines.push('');

    // ---- data.sql ----
    const dataLines = [
        '-- contradictions.db data',
        '-- Generated by dumpDbToSql.js — do not edit by hand; re-run the script.',
        '',
        'PRAGMA foreign_keys = OFF;',
        'BEGIN TRANSACTION;',
        ''
    ];
    const counts = {};
    for (const name of tables) {
        const res = db.exec(`SELECT * FROM ${name} ORDER BY rowid`);
        if (!res.length) { counts[name] = 0; continue; }
        const { columns, values } = res[0];
        counts[name] = values.length;
        const colList = columns.join(', ');
        dataLines.push(`-- ${name} (${values.length} rows)`);
        for (const row of values) {
            const vals = row.map(sqlValue).join(', ');
            dataLines.push(`INSERT INTO ${name} (${colList}) VALUES (${vals});`);
        }
        dataLines.push('');
    }
    dataLines.push('COMMIT;', '');

    db.close();

    if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
    fs.writeFileSync(path.join(OUT_DIR, 'schema.sql'), schemaLines.join('\n'), 'utf8');
    fs.writeFileSync(path.join(OUT_DIR, 'data.sql'), dataLines.join('\n'), 'utf8');

    console.log(`Wrote ${path.join(OUT_DIR, 'schema.sql')} (${tables.length} tables, ${indexes.length} indexes)`);
    console.log(`Wrote ${path.join(OUT_DIR, 'data.sql')}`);
    for (const name of tables) console.log(`  ${name}: ${counts[name]} rows`);
}

main().catch(err => { console.error(err); process.exit(1); });
