/**
 * publishDb.js — Publish contradictions.db (and its reconstruct bundle) to the
 * geBibleApp data location.
 *
 * Layout produced at the destination:
 *   <DEST>/contradictions.db                      (overwritten with the live DB)
 *   <DEST>/contradictions_db/contradictions.sql   (single self-contained reconstruct script)
 *   <DEST>/contradictions_db/buildDbFromSql.js    (Node/sql.js rebuild helper)
 *   <DEST>/contradictions_db/DATABASE.md          (usage guide)
 *
 *   node publishDb.js
 *
 * Env overrides:
 *   GEBIBLE_DATA  destination data dir (default H:\workspace_web\geBibleApp\data)
 *   DB_PATH       source DB (default ./contradictions.db)
 *   NO_BACKUP=1   skip backing up the destination DB before overwrite
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const initSqlJs = require('sql.js');

const DB_PATH = process.env.DB_PATH || './contradictions.db';
const DEST_DATA = process.env.GEBIBLE_DATA || 'H:\\workspace_web\\geBibleApp\\data';
const DEST_DB = path.join(DEST_DATA, 'contradictions.db');
const DEST_BUNDLE = path.join(DEST_DATA, 'contradictions_db');
const SRC_DIR = path.join(__dirname, '..', 'publish');

// Parent-first so the script loads cleanly even if foreign keys are enforced.
const TABLE_ORDER = ['categories', 'contradiction_types', 'scholarly_consensus_levels', 'contradictions', 'answers', 'bible_references'];
// Legacy files from the older two-file publish — superseded by contradictions.sql.
const SUPERSEDED = ['schema.sql', 'data.sql', 'dumpDbToSql.js'];

function sqlValue(v) {
    if (v === null || v === undefined) return 'NULL';
    if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
    if (typeof v === 'bigint') return v.toString();
    if (v instanceof Uint8Array) {
        let hex = '';
        for (const b of v) hex += b.toString(16).padStart(2, '0');
        return `X'${hex}'`;
    }
    return `'${String(v).replace(/'/g, "''")}'`;
}

function sha256(file) {
    return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

/** Build one self-contained SQL string (schema + data) from the live DB. */
function buildCombinedSql(db) {
    const master = db.exec(
        "SELECT type, name, sql FROM sqlite_master " +
        "WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL");
    const objects = master.length
        ? master[0].values.map(([type, name, sql]) => ({ type, name, sql }))
        : [];
    const tableSql = new Map(objects.filter(o => o.type === 'table').map(o => [o.name, o.sql]));
    const indexes = objects.filter(o => o.type === 'index');

    const tables = TABLE_ORDER.filter(t => tableSql.has(t));
    for (const o of objects) {
        if (o.type === 'table' && !tables.includes(o.name)) tables.push(o.name);
    }

    const lines = [
        '-- contradictions.db — full reconstruct (schema + data)',
        '-- Generated by contradictionScraper/publishDb.js — do not edit by hand.',
        '-- Rebuild:  sqlite3 ../contradictions.db < contradictions.sql',
        '',
        'PRAGMA foreign_keys = OFF;',
        'BEGIN TRANSACTION;',
        ''
    ];
    for (const name of [...tables].reverse()) lines.push(`DROP TABLE IF EXISTS ${name};`);
    lines.push('');
    for (const name of tables) lines.push(`${tableSql.get(name)};`, '');
    for (const idx of indexes) lines.push(`${idx.sql};`);
    lines.push('');

    const counts = {};
    for (const name of tables) {
        const res = db.exec(`SELECT * FROM ${name} ORDER BY rowid`);
        if (!res.length) { counts[name] = 0; continue; }
        const { columns, values } = res[0];
        counts[name] = values.length;
        const colList = columns.join(', ');
        lines.push(`-- ${name} (${values.length} rows)`);
        for (const row of values) {
            lines.push(`INSERT INTO ${name} (${colList}) VALUES (${row.map(sqlValue).join(', ')});`);
        }
        lines.push('');
    }
    lines.push('COMMIT;', '');
    return { sql: lines.join('\n'), counts, tables };
}

async function main() {
    if (!fs.existsSync(DB_PATH)) {
        console.error(`Source DB not found: ${path.resolve(DB_PATH)}`);
        process.exit(1);
    }
    if (!fs.existsSync(DEST_DATA)) {
        console.error(`Destination data dir not found: ${DEST_DATA}\n` +
            `(Set GEBIBLE_DATA to override, or create the folder first.)`);
        process.exit(1);
    }
    for (const f of ['buildDbFromSql.js', 'DATABASE.md']) {
        if (!fs.existsSync(path.join(SRC_DIR, f))) {
            console.error(`Missing publish source: ${path.join(SRC_DIR, f)}`);
            process.exit(1);
        }
    }

    // ---- generate the combined SQL from the live DB ----
    const SQL = await initSqlJs();
    const db = new SQL.Database(fs.readFileSync(DB_PATH));
    const { sql, counts, tables } = buildCombinedSql(db);
    db.close();

    if (!fs.existsSync(DEST_BUNDLE)) {
        fs.mkdirSync(DEST_BUNDLE, { recursive: true });
        console.log(`Created ${DEST_BUNDLE}`);
    }

    // ---- 1. publish the DB (with a rolling safety backup) ----
    if (fs.existsSync(DEST_DB) && process.env.NO_BACKUP !== '1') {
        const bak = path.join(DEST_BUNDLE, 'contradictions.db.bak');
        fs.copyFileSync(DEST_DB, bak);
        console.log(`Backed up existing destination DB -> ${bak}`);
    }
    fs.copyFileSync(DB_PATH, DEST_DB);
    const ok = sha256(DB_PATH) === sha256(DEST_DB);
    console.log(`Copied DB -> ${DEST_DB}  (${fs.statSync(DEST_DB).size.toLocaleString()} bytes, sha256 ${ok ? 'match' : 'MISMATCH'})`);
    if (!ok) { console.error('DB copy verification FAILED.'); process.exit(1); }

    // ---- 2. write the reconstruct SQL + support files ----
    fs.writeFileSync(path.join(DEST_BUNDLE, 'contradictions.sql'), sql, 'utf8');
    console.log(`Wrote ${path.join(DEST_BUNDLE, 'contradictions.sql')}`);
    for (const f of ['buildDbFromSql.js', 'DATABASE.md']) {
        fs.copyFileSync(path.join(SRC_DIR, f), path.join(DEST_BUNDLE, f));
        console.log(`Wrote ${path.join(DEST_BUNDLE, f)}`);
    }

    // ---- 3. remove superseded legacy files ----
    for (const f of SUPERSEDED) {
        const p = path.join(DEST_BUNDLE, f);
        if (fs.existsSync(p)) { fs.unlinkSync(p); console.log(`Removed superseded ${p}`); }
    }

    console.log('\nPublished row counts:');
    for (const t of tables) console.log(`  ${String(counts[t]).padStart(4)}  ${t}`);
    console.log('\nDone.');
}

main().catch(err => { console.error(err); process.exit(1); });
