/**
 * snapshotDb.js — Take a complete, timestamped snapshot of contradictions.db
 * into a dated folder under .archive/.
 *
 * Unlike the per-mutation .bak-<ts> files other scripts drop (a bare binary copy),
 * this writes a self-contained snapshot FOLDER you can hand to anyone:
 *
 *   .archive/snapshot-<ts>/
 *     contradictions.db   — verbatim binary copy
 *     schema.sql          — DROP/CREATE for every table + index (recreate-ready)
 *     data.sql            — INSERT statements for every row (recreate-ready)
 *     manifest.json       — timestamp, source path, file sizes, per-table row counts
 *
 * schema.sql + data.sql rebuild the DB with `node .scripts/buildDbFromSql.js`
 * (point DB_PATH/OUT_DIR at the snapshot), so the snapshot survives even if the
 * binary format ever drifts.
 *
 *   node .scripts/snapshotDb.js
 *
 * Env overrides:
 *   DB_PATH     source DB (default ./contradictions.db)
 *   ARCHIVE_DIR snapshot root (default <dir-of-DB>/.archive)
 *   LABEL       extra suffix on the folder name, e.g. LABEL=pre-merge
 */
const fs = require('fs');
const path = require('path');
const initSqlJs = require('sql.js');

const DB_PATH = process.env.DB_PATH || './contradictions.db';
const ARCHIVE_DIR = process.env.ARCHIVE_DIR || path.join(path.dirname(DB_PATH), '.archive');
const LABEL = process.env.LABEL ? `-${process.env.LABEL.replace(/[^A-Za-z0-9._-]/g, '_')}` : '';

// Parent-first so the data file loads cleanly even with foreign keys enforced.
const TABLE_ORDER = ['categories', 'contradiction_types', 'scholarly_consensus_levels', 'contradictions', 'answers', 'bible_references'];

function sqlValue(v) {
    if (v === null || v === undefined) return 'NULL';
    if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
    if (typeof v === 'bigint') return v.toString();
    if (v instanceof Uint8Array) {
        let hex = '';
        for (const b of v) hex += b.toString(16).padStart(2, '0');
        return `X'${hex}'`;
    }
    return `'${String(v).replace(/'/g, "''")}'`;
}

function humanSize(bytes) {
    if (bytes < 1024) return `${bytes} B`;
    const units = ['KB', 'MB', 'GB'];
    let n = bytes / 1024, i = 0;
    while (n >= 1024 && i < units.length - 1) { n /= 1024; i++; }
    return `${n.toFixed(1)} ${units[i]}`;
}

async function main() {
    if (!fs.existsSync(DB_PATH)) {
        console.error(`Source DB not found: ${DB_PATH}`);
        process.exit(1);
    }

    const SQL = await initSqlJs();
    const buf = fs.readFileSync(DB_PATH);
    const db = new SQL.Database(buf);

    // ---- collect schema objects from sqlite_master ----
    const master = db.exec(
        "SELECT type, name, tbl_name, sql FROM sqlite_master " +
        "WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL"
    );
    const objects = master.length
        ? master[0].values.map(([type, name, tblName, sql]) => ({ type, name, tblName, sql }))
        : [];

    const tableSql = new Map(objects.filter(o => o.type === 'table').map(o => [o.name, o.sql]));
    const indexes = objects.filter(o => o.type === 'index');

    const tables = TABLE_ORDER.filter(t => tableSql.has(t));
    for (const o of objects) {
        if (o.type === 'table' && !tables.includes(o.name)) tables.push(o.name);
    }

    // ---- schema.sql ----
    const schemaLines = [
        '-- contradictions.db schema',
        '-- Generated by snapshotDb.js — do not edit by hand.',
        '',
        'PRAGMA foreign_keys = OFF;',
        ''
    ];
    for (const name of [...tables].reverse()) schemaLines.push(`DROP TABLE IF EXISTS ${name};`);
    schemaLines.push('');
    for (const name of tables) schemaLines.push(`${tableSql.get(name)};`, '');
    for (const idx of indexes) schemaLines.push(`${idx.sql};`);
    schemaLines.push('');

    // ---- data.sql ----
    const dataLines = [
        '-- contradictions.db data',
        '-- Generated by snapshotDb.js — do not edit by hand.',
        '',
        'PRAGMA foreign_keys = OFF;',
        'BEGIN TRANSACTION;',
        ''
    ];
    const counts = {};
    for (const name of tables) {
        const res = db.exec(`SELECT * FROM ${name} ORDER BY rowid`);
        if (!res.length) { counts[name] = 0; continue; }
        const { columns, values } = res[0];
        counts[name] = values.length;
        const colList = columns.join(', ');
        dataLines.push(`-- ${name} (${values.length} rows)`);
        for (const row of values) {
            dataLines.push(`INSERT INTO ${name} (${colList}) VALUES (${row.map(sqlValue).join(', ')});`);
        }
        dataLines.push('');
    }
    dataLines.push('COMMIT;', '');

    db.close();

    // ---- write the snapshot folder ----
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const snapDir = path.join(ARCHIVE_DIR, `snapshot-${ts}${LABEL}`);
    fs.mkdirSync(snapDir, { recursive: true });

    const dbCopy = path.join(snapDir, path.basename(DB_PATH));
    fs.copyFileSync(DB_PATH, dbCopy);
    fs.writeFileSync(path.join(snapDir, 'schema.sql'), schemaLines.join('\n'), 'utf8');
    fs.writeFileSync(path.join(snapDir, 'data.sql'), dataLines.join('\n'), 'utf8');

    const manifest = {
        createdAt: new Date().toISOString(),
        source: path.resolve(DB_PATH),
        dbBytes: buf.length,
        tables: counts,
        totalRows: Object.values(counts).reduce((a, b) => a + b, 0),
        files: [path.basename(DB_PATH), 'schema.sql', 'data.sql', 'manifest.json'],
        rebuild: 'DB_PATH=./contradictions.db OUT_DIR=<this folder> node .scripts/buildDbFromSql.js',
    };
    fs.writeFileSync(path.join(snapDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');

    // ---- report ----
    console.log(`Snapshot: ${snapDir}`);
    console.log(`  ${path.basename(DB_PATH)}  ${humanSize(buf.length)}`);
    console.log(`  schema.sql + data.sql  (${tables.length} tables, ${indexes.length} indexes)`);
    for (const name of tables) console.log(`    ${name}: ${counts[name]} rows`);
    console.log(`  manifest.json  (total rows: ${manifest.totalRows})`);
}

main().catch(err => { console.error(err); process.exit(1); });
